id: P005457
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016263
  title: ཀརྨ་པ་སྒར་བསངས་ཆེན་མོ
  author: ''
  volumes:
    dc9ec199d63644e48b279c835693168e:
      image_group_id: I00JW501159
      title: ''
      volume_number: 1
      total_pages: 634
      base_file: v001.txt
